# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convolution.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 422)
        self.groupBox4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox4.setGeometry(QtCore.QRect(180, 210, 131, 191))
        self.groupBox4.setObjectName("groupBox4")
        self.btn41 = QtWidgets.QPushButton(self.groupBox4)
        self.btn41.setGeometry(QtCore.QRect(10, 30, 110, 29))
        self.btn41.setObjectName("btn41")
        self.btn42 = QtWidgets.QPushButton(self.groupBox4)
        self.btn42.setGeometry(QtCore.QRect(10, 70, 110, 29))
        self.btn42.setObjectName("btn42")
        self.btn43 = QtWidgets.QPushButton(self.groupBox4)
        self.btn43.setGeometry(QtCore.QRect(10, 110, 110, 29))
        self.btn43.setObjectName("btn43")
        self.btn44 = QtWidgets.QPushButton(self.groupBox4)
        self.btn44.setGeometry(QtCore.QRect(10, 150, 110, 29))
        self.btn44.setObjectName("btn44")
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 171, 191))
        self.groupBox1.setObjectName("groupBox1")
        self.btn11 = QtWidgets.QPushButton(self.groupBox1)
        self.btn11.setGeometry(QtCore.QRect(0, 30, 121, 29))
        self.btn11.setObjectName("btn11")
        self.btn12 = QtWidgets.QPushButton(self.groupBox1)
        self.btn12.setGeometry(QtCore.QRect(0, 70, 161, 29))
        self.btn12.setObjectName("btn12")
        self.btn13 = QtWidgets.QPushButton(self.groupBox1)
        self.btn13.setGeometry(QtCore.QRect(0, 110, 141, 29))
        self.btn13.setObjectName("btn13")
        self.btn14 = QtWidgets.QPushButton(self.groupBox1)
        self.btn14.setGeometry(QtCore.QRect(0, 150, 101, 29))
        self.btn14.setObjectName("btn14")
        self.groupBox2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox2.setGeometry(QtCore.QRect(180, 10, 181, 111))
        self.groupBox2.setObjectName("groupBox2")
        self.btn21 = QtWidgets.QPushButton(self.groupBox2)
        self.btn21.setGeometry(QtCore.QRect(10, 30, 161, 29))
        self.btn21.setObjectName("btn21")
        self.btn22 = QtWidgets.QPushButton(self.groupBox2)
        self.btn22.setGeometry(QtCore.QRect(10, 70, 151, 29))
        self.btn22.setObjectName("btn22")
        self.groupBox3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox3.setGeometry(QtCore.QRect(370, 10, 291, 351))
        self.groupBox3.setObjectName("groupBox3")
        self.groupBox31 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox31.setGeometry(QtCore.QRect(10, 30, 261, 261))
        self.groupBox31.setObjectName("groupBox31")
        self.groupBox311 = QtWidgets.QGroupBox(self.groupBox31)
        self.groupBox311.setGeometry(QtCore.QRect(10, 30, 241, 191))
        self.groupBox311.setObjectName("groupBox311")
        self.label = QtWidgets.QLabel(self.groupBox311)
        self.label.setGeometry(QtCore.QRect(0, 40, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox311)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox311)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox311)
        self.label_4.setGeometry(QtCore.QRect(0, 160, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox311)
        self.label_5.setGeometry(QtCore.QRect(180, 40, 41, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox311)
        self.label_6.setGeometry(QtCore.QRect(180, 120, 41, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox311)
        self.label_7.setGeometry(QtCore.QRect(180, 160, 41, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox311)
        self.lineEdit_1.setGeometry(QtCore.QRect(50, 40, 113, 29))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox311)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 80, 113, 29))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox311)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 120, 113, 29))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox311)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 160, 113, 29))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.btn31 = QtWidgets.QPushButton(self.groupBox31)
        self.btn31.setGeometry(QtCore.QRect(0, 230, 261, 29))
        self.btn31.setObjectName("btn31")
        self.btn32 = QtWidgets.QPushButton(self.groupBox3)
        self.btn32.setGeometry(QtCore.QRect(10, 310, 261, 29))
        self.btn32.setObjectName("btn32")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox4.setTitle(_translate("Dialog", "4. Convolution"))
        self.btn41.setText(_translate("Dialog", "1. Gaussian"))
        self.btn42.setText(_translate("Dialog", "2. Sobel X"))
        self.btn43.setText(_translate("Dialog", "3. Sobel Y"))
        self.btn44.setText(_translate("Dialog", "4. Magnitude"))
        self.groupBox1.setTitle(_translate("Dialog", "1. Image Processing"))
        self.btn11.setText(_translate("Dialog", "1. Load Image"))
        self.btn12.setText(_translate("Dialog", "2. Color Conversion"))
        self.btn13.setText(_translate("Dialog", "3. Image Flipping"))
        self.btn14.setText(_translate("Dialog", "4. Blending"))
        self.groupBox2.setTitle(_translate("Dialog", "2. Adaptive Threshold"))
        self.btn21.setText(_translate("Dialog", "1. Global Threshold"))
        self.btn22.setText(_translate("Dialog", "2. Local Threshold"))
        self.groupBox3.setTitle(_translate("Dialog", "3. image Transformation"))
        self.groupBox31.setTitle(_translate("Dialog", "3.1 Rot,Scale,Tranlate"))
        self.groupBox311.setTitle(_translate("Dialog", "Parameter"))
        self.label.setText(_translate("Dialog", "Angel:"))
        self.label_2.setText(_translate("Dialog", "Scale:"))
        self.label_3.setText(_translate("Dialog", "Tx:"))
        self.label_4.setText(_translate("Dialog", "Ty:"))
        self.label_5.setText(_translate("Dialog", "deg"))
        self.label_6.setText(_translate("Dialog", "pixel"))
        self.label_7.setText(_translate("Dialog", "pixel"))
        self.btn31.setText(_translate("Dialog", "3.1 Rotation,scaling,translation"))
        self.btn32.setText(_translate("Dialog", "3.2 Perspective Transform"))
